In [66]:
import glob 
import astropy.io.fits as fits
import os
import numpy as np

In [67]:
data_dir = '/home/pi/DATA/astro/rozhen/20180517/fit/gd319/'
ext = '*.fit'

In [68]:
images = sorted(glob.glob(os.path.join(data_dir, ext)))
print('test image name:', os.path.basename(images[0]))

test image name: gd319_hwp_wp_r_000_1.fit


In [69]:
split_by = '_'
# counts from zero!
color_name_pos = 3
angle_name_pos = 4

# TEST

In [70]:
test_name = os.path.basename(images[0])
color = test_name.split(split_by)[color_name_pos]
angle = test_name.split(split_by)[angle_name_pos]
print(test_name)
print('color name:', color)
print('angle name:', angle)

gd319_hwp_wp_r_000_1.fit
color name: r
angle name: 000


In [71]:
name_to_angle = {'000': 0.0,
                 '022': 22.5,
                 '045': 45.0,
                 '067': 67.5}

In [72]:
for im in images:
    
    print(os.path.basename(im))
    color = os.path.basename(im.split(split_by)[color_name_pos])
    angle = os.path.basename(im.split(split_by)[angle_name_pos])
    print(color, angle, name_to_angle[angle])
    
    hdu = fits.open(im, mode='update')
    data = hdu[0].data
    hdr = hdu[0].header
    hdr['FILTER'] = str(name_to_angle[angle]) + '-' + color.upper()
    hdu[0].header = hdr
    
    data = np.where(data < 0, -1*data+32768, data)
    print(data)
    hdu.flush()
    

gd319_hwp_wp_r_000_1.fit
r 000 0.0
[[94 94 97 ... 94 99 97]
 [90 99 95 ... 98 97 96]
 [93 97 96 ... 94 96 93]
 ...
 [89 94 92 ... 91 95 96]
 [87 94 97 ... 93 96 98]
 [92 94 92 ... 96 95 93]]
gd319_hwp_wp_r_000_2.fit
r 000 0.0
[[ 90  92  96 ...  94  99  94]
 [ 91  96  97 ...  95  93  93]
 [ 91  96  94 ...  95  96  96]
 ...
 [ 92  95  90 ...  95  92 100]
 [ 91  94  93 ...  93  95  93]
 [ 88  97  94 ...  96  95  96]]
gd319_hwp_wp_r_000_3.fit
r 000 0.0
[[95 93 96 ... 98 96 94]
 [90 99 97 ... 97 97 98]
 [90 95 97 ... 97 96 98]
 ...
 [88 95 95 ... 96 98 96]
 [91 93 93 ... 98 94 96]
 [90 93 93 ... 93 94 98]]
gd319_hwp_wp_r_000_4.fit
r 000 0.0
[[90 95 93 ... 99 97 94]
 [93 92 97 ... 97 94 97]
 [89 97 95 ... 97 93 94]
 ...
 [87 94 94 ... 96 96 94]
 [91 93 94 ... 96 95 98]
 [91 91 93 ... 96 99 95]]
gd319_hwp_wp_r_000_5.fit
r 000 0.0
[[ 93  95  93 ...  96  95  94]
 [ 88  98  98 ...  93  94  94]
 [ 91  95  97 ...  95  98  96]
 ...
 [ 89  91  96 ...  95  99  96]
 [ 88  94  94 ... 100  93  93]
 [ 89